### ISSUE TITLE
SingleStore DB support Array<struct> column types ?

### ISSUE THREAD

**Issue by samminen** [memsql/singlestore-spark-connector#67]
Hello Team,
   Like hive, does MEMSQL support table column datatype array<struct> as show below ?
   if yes, how to extract array<struct> inner columns ? explode lateral view we have in hive, anything similar ?

 column name                            |  Datatype
 -----------------------------------------------------------------------------------------
 diagnoses                              | array<struct<column1 string, column2 double>>

**Comment by rpourzand** [comment]
Hi Samminen, 

SingleStore does not support a native array column type. 

However, you can call an array within a stored procedure (MPSQL)
See reference here: https://docs.singlestore.com/v7.3/reference/sql-reference/procedural-sql-reference/array/

Also, as a workaround, you can use the JSON column type to store data in a JSON array, and use our functions to extract data, like JSON_TO_ARRAY, or write your own function to do so.

https://docs.singlestore.com/v7.3/reference/sql-reference/json-functions/json_to_array/

**Comment by blinov-ivan** [comment]
Hi @samminen ,
close this issue as there's no response from you.

Please, feel free to reopen this issue if you have some additional questions
