### ISSUE TITLE
supported features for singlestore-spark-connector_2.11....

### ISSUE THREAD

**Issue by bolcman** [memsql/singlestore-spark-connector#73]
Hi, 

Are new features available for connector version 'singlestore-spark-connector_2.11:3.1.2-spark-2.4.7' (Spark 2.x) ?

I tried to pass something like this:

enableParallelRead  = automaticLite

 but got wrong value message...

also I have SingleStoreDB version 7.5+

Thanks, 
Aleks

**Comment by AdalbertMemSQL** [comment]
Hi,

New features are described in the release [highlights](https://docs.singlestore.com/db/v7.8/en/load-data/load-data-from-a-data-source/load-data-from-spark/getting-started.html#release-highlights-652850).
  More details can be found in the [CHANGELOG](https://github.com/memsql/singlestore-spark-connector/blob/master/CHANGELOG).

enableParallelRead is available starting from 3.2 version of the driver.
