### ISSUE TITLE
support partial column list when using .write()

### ISSUE THREAD

**Issue by ronassa** [memsql/singlestore-spark-connector#74]
when writing data frame to SingleStore using [insert batch](https://github.com/memsql/singlestore-spark-connector/blob/d6dee572cf1920dec78348f2d7eb304b425f48fb/src/main/scala/com/singlestore/spark/SinglestoreBatchInsertWriter.scala#L19) it expecting all columns of the tables to be included in the data frame, otherwise, it fails. 

why not use the data frame columns from the schema to support partial column insert? 

if you agree with the direction, do you accept pull requests?

**Comment by AdalbertMemSQL** [comment]
Hi, @ronassa 
This request sounds reasonable. 
I agree with a direction and accept pull requests.

**Comment by ronassa** [comment]
@AdalbertMemSQL, since I posted this comment, it's already been solved.
